/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import classes.Imovel;
import gerenciador.GerenciadorImovel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rangel
 */
public class FrCadImovel extends javax.swing.JFrame {

    private String imovelEscolhido;
    private boolean editando;
    private GerenciadorImovel gerente;
    public FrCadImovel() {
        initComponents();
        this.editando = false;
        this.imovelEscolhido = "";
        this.gerente = new GerenciadorImovel();
        this.habilitarCampos(false);
        this.limparCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        panBotoes = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        panDados = new javax.swing.JPanel();
        lblTipo = new javax.swing.JLabel();
        edtTipo = new javax.swing.JTextField();
        lblQuartos = new javax.swing.JLabel();
        edtQuartos = new javax.swing.JTextField();
        lblArea = new javax.swing.JLabel();
        edtArea = new javax.swing.JTextField();
        lblBanheiros = new javax.swing.JLabel();
        edtBanheiros = new javax.swing.JTextField();
        edtPreco = new javax.swing.JTextField();
        lblPreco = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtListagem = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Cadastro de Imóveis");

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/novo-arquivo.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        panBotoes.add(btnNovo);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar-texto.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        panBotoes.add(btnEditar);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panBotoes.add(btnCancelar);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excluir.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        panBotoes.add(btnExcluir);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salvar-arquivo.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        panBotoes.add(btnSalvar);

        lblTipo.setText("Tipo:");

        lblQuartos.setText("Nº Quartos:");

        lblArea.setText("Área:");

        lblBanheiros.setText("Nº Banheiros:");

        edtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtPrecoActionPerformed(evt);
            }
        });

        lblPreco.setText("Preço:");

        javax.swing.GroupLayout panDadosLayout = new javax.swing.GroupLayout(panDados);
        panDados.setLayout(panDadosLayout);
        panDadosLayout.setHorizontalGroup(
            panDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDadosLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDadosLayout.createSequentialGroup()
                        .addComponent(lblTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(panDadosLayout.createSequentialGroup()
                        .addComponent(lblArea)
                        .addGap(16, 16, 16)))
                .addGroup(panDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(edtArea)
                    .addComponent(edtTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(panDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panDadosLayout.createSequentialGroup()
                        .addComponent(lblQuartos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edtQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panDadosLayout.createSequentialGroup()
                        .addComponent(lblBanheiros)
                        .addGap(18, 18, 18)
                        .addComponent(edtBanheiros, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPreco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edtPreco)
                .addContainerGap())
        );
        panDadosLayout.setVerticalGroup(
            panDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDadosLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTipo)
                        .addComponent(edtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblQuartos)
                        .addComponent(edtQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblArea)
                    .addGroup(panDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(edtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblBanheiros)
                        .addComponent(edtBanheiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(panDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreco)
                    .addComponent(edtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        edtListagem.setColumns(20);
        edtListagem.setRows(5);
        jScrollPane1.setViewportView(edtListagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panDados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.limparCampos();
        this.habilitarCampos(true);
        this.editando = false;
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        this.imovelEscolhido = JOptionPane.showInputDialog("Informe o tipo do imóvel: ", "");
        Imovel imovelEditado = this.gerente.buscarImovel(imovelEscolhido);

        if(imovelEditado != null){
            this.editando = true;
            this.limparCampos();
            this.habilitarCampos(true);

            objetoParaCampos(imovelEditado);

        }else{
            System.out.println("Nome do imóvel inválido ou sem cadastro.");
            JOptionPane.showMessageDialog(this , "Nome do imóvel inválido ou sem cadastro.");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.limparCampos();
        this.habilitarCampos(false);
        this.editando = false;
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        this.imovelEscolhido = JOptionPane.showInputDialog("Informe o tipo do imóvel: ", "");

        Imovel imovel = this.gerente.buscarImovel(imovelEscolhido);

        if(imovel == null){
            JOptionPane.showMessageDialog(this, "Nome do imóvel inválido ou sem cadastro.");
        }else{
            this.gerente.removerImovel(imovelEscolhido);
            JOptionPane.showMessageDialog(this, "Nome do imóvel excluído com sucesso");
        }
        String listagem = this.gerente.toString();
        edtListagem.setText(listagem);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Imovel novoImovel = this.camposParaObjeto();

        if(this.editando == true)
        this.gerente.atualizarImovel(this.imovelEscolhido , novoImovel);
        else
        this.gerente.adicionarImovel(novoImovel);

        this.limparCampos();
        this.habilitarCampos(false);
        this.editando = false;

        String listagem = gerente.toString();
        edtListagem.setText(listagem);

        gerente.salvarEmXML("ListagemImoveis.xml"); // Isso salva em arquivo xml
        //gerente.salvarNoArquivo("ListagemImoveis.json"); //Isso salva em arquivo .json
        //gerente.salvarEmCSV("ListagemImoveis.csv"); // Isso salva em arquivo CSV
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void edtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtPrecoActionPerformed
    
    public void objetoParaCampos(Imovel imovel){
        edtTipo.setText(imovel.getTipoImovel());
        edtQuartos.setText(imovel.getQtdQuartos()+ "");
        edtBanheiros.setText(imovel.getQtdBanheiros() + "");
        edtArea.setText(imovel.getTamArea() + "");
        edtPreco.setText(imovel.getPreco() + "");
    }
    public Imovel camposParaObjeto(){
        Imovel imovel = new Imovel();
        imovel.setTipoImovel(edtTipo.getText());
        
        String quartosStr = edtQuartos.getText();
        if(!quartosStr.isEmpty()){
            int quartos = Integer.parseInt(quartosStr);
            imovel.setQtdQuartos(quartos);
        }
        String banheirosStr = edtBanheiros.getText();
        if(!banheirosStr.isEmpty()){
            int banheiros = Integer.parseInt(banheirosStr);
            imovel.setQtdBanheiros(banheiros);
        }
        String areaStr = edtArea.getText();
        if(!areaStr.isEmpty()){
            double area = Double.parseDouble(areaStr);
            imovel.setTamArea(area);
        }
        
        String precoStr = edtPreco.getText();
        if(!precoStr.isEmpty()){
            double preco = Double.parseDouble(precoStr);
            imovel.setPreco(preco);
        }
        return imovel;
    }
    /**
     * @param args the command line arguments
     */
    public void habilitarCampos(boolean flag){
        this.edtTipo.setEnabled(flag);
        this.edtQuartos.setEnabled(flag);
        this.edtBanheiros.setEnabled(flag);
        this.edtArea.setEnabled(flag);
        this.edtPreco.setEnabled(flag);
    }
    public void limparCampos(){
        this.edtTipo.setText("");
        this.edtQuartos.setText("");
        this.edtBanheiros.setText("");
        this.edtArea.setText("");
        this.edtPreco.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField edtArea;
    private javax.swing.JTextField edtBanheiros;
    private javax.swing.JTextArea edtListagem;
    private javax.swing.JTextField edtPreco;
    private javax.swing.JTextField edtQuartos;
    private javax.swing.JTextField edtTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblBanheiros;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblQuartos;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panBotoes;
    private javax.swing.JPanel panDados;
    // End of variables declaration//GEN-END:variables
}
